const sliderHomeController = require('../controller/sliderHomeController')
const sliderSponsorController = require('../controller/sliderSponsorHomeController')
const modalPromoHomeController = require('../controller/modalPromoHomeController')
const formPromoHomeController = require('../controller/formPromoHomeController')
const paketController = require('../controller/paketController')
const materiController = require('../controller/materiController')
const userController = require('../users/userController')
const adminController = require('../controller/adminController')
const newsController = require('../controller/newsController')
const contactController = require('../controller/contactController')
const hasilKaryaController = require('../controller/hasilKaryaController')

module.exports = app => {
    app.post('/slider', sliderHomeController.addSlider)
    app.get('/slider/:id', sliderHomeController.detailSlider)
    app.get('/slider', sliderHomeController.listSlider)
    app.put('/slider/:id', sliderHomeController.updateSlider)
    app.delete('/slider/:id', sliderHomeController.deleteSlider)

    app.post('/slider-sponsor', sliderSponsorController.addSponsor)
    app.get('/slider-sponsor/:id', sliderSponsorController.detailSponsor)
    app.get('/slider-sponsor', sliderSponsorController.listSponsor)
    app.put('/slider-sponsor', sliderSponsorController.updateSponsor)
    app.delete('/slider-sponsor', sliderSponsorController.deleteSponsor)

    app.post('/modal-promo', modalPromoHomeController.addModalPromo)
    app.get('/modal-promo/:id', modalPromoHomeController.detailModalPromo)
    app.get('/modal-promo', modalPromoHomeController.listModalPromo)
    app.put('/modal-promo/:id', modalPromoHomeController.updateModalPromo)
    app.delete('/modal-promo/:id', modalPromoHomeController.deleteModalPromo)

    app.post('/form-promo', formPromoHomeController.addFormPromo)
    app.get('/form-promo/:id', formPromoHomeController.detailFormPromo)
    app.get('/form-promo', formPromoHomeController.listFormPromo)
    app.put('/form-promo/:id', formPromoHomeController.updateFormPromo)
    app.delete('/form-promo/:id', formPromoHomeController.deleteFormPromo)

    app.post('/materi', materiController.addMateri)
    app.get('/materi/:id', materiController.detailMateri)
    app.get('/materi', materiController.listMateri)
    app.put('/materi/:id', materiController.updateMateri)
    app.delete('/materi/:id', materiController.deleteMateri)

    app.post('/paket', paketController.addPaket)
    app.get('/paket/:id', paketController.detailPaket)
    app.get('/paket', paketController.listPaket)
    app.put('/paket/:id', paketController.updatePaket)
    app.delete('/paket/:id', paketController.deletePaket)

    app.post('/users/authenticate', userController.authenticate )
    app.post('/users/register', userController.register)
    // app.get('/users/logout', userController.logout)
    app.get('/users', userController.getAll)
    app.get('/users/current', userController.getCurrent)
    app.get('/users/:id', userController.getById)
    app.put('/users/:id', userController.update)
    app.delete('/users/:id', userController._delete)

    app.post('/admin', adminController.addAdmin)
    app.get('/admin/:id', adminController.detailAdmin)
    app.get('/admin', adminController.listAdmin)
    app.put('/admin/:id', adminController.updatesAdmin)
    app.delete('/admin/:id', adminController.deleteAdmin)

    app.post('/news', newsController.addNews)
    app.get('/news/:id', newsController.detailNews)
    app.get('/news/', newsController.listNews)
    app.put('/news/:id', newsController.updateNews)
    app.delete('/news/:id', newsController.deleteNews)

    app.post('/contact', contactController.addContact)
    app.get('/contact/:id', contactController.detailContact)
    app.get('/contact', contactController.listContact)
    app.put('/contact/:id', contactController.updateContact)
    app.delete('/contact/:id', contactController.deleteContact)

    app.post('/hasil-karya', hasilKaryaController.addHasilKarya)
    app.get('/hasil-karya/:id', hasilKaryaController.detailHasilKarya)
    app.get('/hasil-karya/', hasilKaryaController.listHasilKarya)
    app.put('/hasil-karya/:id', hasilKaryaController.updateHasilKarya)
    app.delete('/hasil-karya/:id', hasilKaryaController.deleteHasilKarya)
}